language: node_js

node_js:
  # Node 10.3+ includes npm@6 which has good "npm ci" command
  - 10.8


before_script:
    - npm install
    - rm -rf nod_modules/ package-lock.json

script:
    - npm test:e2e