language: node_js

node_js:
    - "node"
    - "14"
    - "13"
    - "12"

sudo: false

git:
    submodules: false

before_script:
    - npm install
    - rm -rf nod_modules/ package-lock.json

script:
    - npm run test:e2e